# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='in_print',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
