# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logReg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorLike', to='logReg.UserDB')),
            ],
        ),
        migrations.CreateModel(
            name='SecretDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.TextField(default=None)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorSecret', to='logReg.UserDB')),
            ],
        ),
        migrations.AddField(
            model_name='likedb',
            name='secret',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretLike', to='secrets.SecretDB'),
        ),
    ]
