# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorsDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=92)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersAuthors', to='users.UsersDB')),
            ],
        ),
        migrations.CreateModel(
            name='BooksDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorsBooks', to='books.AuthorsDB')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersBooks', to='users.UsersDB')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewsDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booksReviews', to='books.BooksDB')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersReviews', to='users.UsersDB')),
            ],
        ),
    ]
